server:
  port: 7777
spring:
#  数据库
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Abc123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      逻辑删除字段，名字叫delFlag
      logic-delete-field: delFlag
#      删除的值为1
      logic-delete-value: 1
      logic-not-delete-value: 0
#      主键自增
      id-type: auto

huaweicloud-obs:
  access-key: OIX7LCLPPYHRMYO7BLXZ
  secret-key: zYrDnBlJWiZW8q9GpjWksZrMXXvf24yRBIPtTz2w
  end-point: https://obs.cn-south-1.myhuaweicloud.com
  bucket-name: clayicarus-blog